services:
  backup:
    build: .
    env_file: .env
    volumes:
      - ./backups:/backups
    image: mongodb-atlas-backup:latest
    container_name: mongodb-atlas-backup
    restart: unless-stopped
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'
